#!/usr/bin/python3
from datetime import date
import os
from getNeofetchDistros import getRandDistro
path = '/home/maml/projects/startup/date.txt'
if os.path.exists(path) == False:
    with open(path, 'w') as f:
        f.write('')

f = open(path, 'r')
today = date.today().strftime('%d/%m/%Y')
fileDate = f.read()
f.close()

if fileDate == '' or today != fileDate:
    os.system('neofetch --ascii_distro ' + getRandDistro())
    with open(path, 'w') as f:
        f.write(today)
